const exercises=[
["Liegestütze","8–15 Wdh.","Körper gerade halten, Brust Richtung Boden senken und wieder hochdrücken.","push"],
["Kniebeugen","15–20 Wdh.","Hüfte nach hinten, Rücken gerade halten.","squat"],
["Plank","30–60 Sek.","Bauch und Gesäß anspannen, Körperlinie halten.","plank"],
["Glute Bridge","12–20 Wdh.","Hüfte kontrolliert nach oben drücken.","bridge"],
["Ausfallschritte","10–12 je Bein","Großen Schritt nach vorne, Knie stabil halten.","lunge"],
["Superman","12–15 Wdh.","Arme und Beine anheben, kurz halten.","super"],
["Mountain Climbers","30 Sek.","Knie abwechselnd schnell zur Brust ziehen.","climb"],
["Dips am Stuhl","8–15 Wdh.","Ellenbogen beugen und wieder hochdrücken.","dip"]
];
const svg={
push:`<svg viewBox="0 0 320 180"><rect x="20" y="145" width="280" height="5" fill="#cbd5e1"/><circle cx="68" cy="84" r="16" fill="#f0b37e" stroke="#111" stroke-width="3"/><path d="M84 90 L190 110 L260 116" stroke="#111" stroke-width="13" fill="none" stroke-linecap="round"/><path d="M125 98 L108 145 M205 112 L200 145 M258 116 L292 138 M258 116 L286 96" stroke="#111" stroke-width="8" fill="none" stroke-linecap="round"/></svg>`,
squat:`<svg viewBox="0 0 320 180"><rect x="50" y="150" width="220" height="5" fill="#cbd5e1"/><circle cx="155" cy="40" r="16" fill="#f0b37e" stroke="#111" stroke-width="3"/><path d="M156 56 L148 98 L190 112" stroke="#111" stroke-width="13" fill="none" stroke-linecap="round"/><path d="M150 72 L108 88 M156 72 L205 88 M190 112 L238 148 M148 98 L108 148" stroke="#111" stroke-width="8" fill="none" stroke-linecap="round"/></svg>`,
plank:`<svg viewBox="0 0 320 180"><rect x="20" y="145" width="280" height="5" fill="#cbd5e1"/><circle cx="75" cy="95" r="16" fill="#f0b37e" stroke="#111" stroke-width="3"/><path d="M90 100 L200 108 L270 118" stroke="#111" stroke-width="13" fill="none" stroke-linecap="round"/><path d="M120 103 L98 145 M145 105 L130 145 M270 118 L295 145 M265 118 L286 145" stroke="#111" stroke-width="8" fill="none" stroke-linecap="round"/></svg>`,
bridge:`<svg viewBox="0 0 320 180"><rect x="20" y="145" width="280" height="5" fill="#cbd5e1"/><circle cx="65" cy="122" r="15" fill="#f0b37e" stroke="#111" stroke-width="3"/><path d="M80 122 L140 92 L210 92 L260 120" stroke="#111" stroke-width="13" fill="none" stroke-linecap="round"/><path d="M258 120 L285 145 M215 95 L230 145 M95 127 L65 145" stroke="#111" stroke-width="8" fill="none" stroke-linecap="round"/></svg>`,
lunge:`<svg viewBox="0 0 320 180"><rect x="35" y="150" width="250" height="5" fill="#cbd5e1"/><circle cx="150" cy="38" r="16" fill="#f0b37e" stroke="#111" stroke-width="3"/><path d="M150 55 L150 95 L190 117" stroke="#111" stroke-width="13" fill="none" stroke-linecap="round"/><path d="M148 72 L115 88 M152 72 L190 88 M150 96 L95 145 M190 117 L240 145" stroke="#111" stroke-width="8" fill="none" stroke-linecap="round"/></svg>`,
super:`<svg viewBox="0 0 320 180"><rect x="30" y="145" width="260" height="5" fill="#cbd5e1"/><circle cx="80" cy="92" r="15" fill="#f0b37e" stroke="#111" stroke-width="3"/><path d="M96 95 L190 105 L250 98" stroke="#111" stroke-width="13" fill="none" stroke-linecap="round"/><path d="M142 100 L210 65 M148 103 L212 135 M245 98 L285 72 M245 101 L285 128" stroke="#111" stroke-width="8" fill="none" stroke-linecap="round"/></svg>`,
climb:`<svg viewBox="0 0 320 180"><rect x="20" y="146" width="280" height="5" fill="#cbd5e1"/><circle cx="76" cy="78" r="16" fill="#f0b37e" stroke="#111" stroke-width="3"/><path d="M92 84 L190 105 L260 115" stroke="#111" stroke-width="13" fill="none" stroke-linecap="round"/><path d="M125 92 L103 145 M188 105 L147 143 M258 115 L292 142 M258 115 L278 85" stroke="#111" stroke-width="8" fill="none" stroke-linecap="round"/></svg>`,
dip:`<svg viewBox="0 0 320 180"><rect x="210" y="70" width="75" height="10" rx="3" fill="#334155"/><path d="M220 80 L220 150 M275 80 L275 150" stroke="#334155" stroke-width="8"/><rect x="35" y="150" width="250" height="5" fill="#cbd5e1"/><circle cx="130" cy="78" r="16" fill="#f0b37e" stroke="#111" stroke-width="3"/><path d="M132 94 L170 120 L215 113" stroke="#111" stroke-width="13" fill="none" stroke-linecap="round"/><path d="M170 120 L135 147 M175 120 L225 147 M205 112 L225 80 M217 114 L235 82" stroke="#111" stroke-width="8" fill="none" stroke-linecap="round"/></svg>`
};
const key="calisthenicsPWA"; const today=new Date().toISOString().slice(0,10);
function get(){return JSON.parse(localStorage.getItem(key)||"{}")} function set(d){localStorage.setItem(key,JSON.stringify(d))}
function ensure(){let d=get(); if(!d[today]) d[today]={done:false,ex:{}}; set(d); return d}
document.getElementById("dateText").textContent=new Date().toLocaleDateString("de-DE",{weekday:"long",day:"2-digit",month:"long",year:"numeric"});
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.page").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.page).classList.add("active");render()});
function renderExercises(){let d=ensure(), wrap=document.getElementById("exerciseList");wrap.innerHTML="";exercises.forEach((e,i)=>{let v=d[today].ex[i]||{};let el=document.createElement("article");el.className="exercise";el.innerHTML=`<div class="art">${svg[e[3]]}</div><div class="body"><h3>${i+1}. ${e[0]}</h3><div class="amount">${e[1]}</div><p class="info">${e[2]}</p><div class="inputs"><input placeholder="Wdh./Zeit" data-i="${i}" data-f="value" value="${v.value||""}"><input placeholder="Sätze" data-i="${i}" data-f="sets" value="${v.sets||""}"><textarea placeholder="Notizen" data-i="${i}" data-f="note">${v.note||""}</textarea></div><label class="check">Erledigt <input type="checkbox" data-i="${i}" ${v.done?"checked":""}></label></div>`;wrap.appendChild(el)});wrap.querySelectorAll("input:not([type=checkbox]),textarea").forEach(x=>x.oninput=e=>{let d=ensure(),i=e.target.dataset.i,f=e.target.dataset.f;if(!d[today].ex[i])d[today].ex[i]={};d[today].ex[i][f]=e.target.value;set(d);stats()});wrap.querySelectorAll("input[type=checkbox]").forEach(x=>x.onchange=e=>{let d=ensure(),i=e.target.dataset.i;if(!d[today].ex[i])d[today].ex[i]={};d[today].ex[i].done=e.target.checked;set(d);stats()})}
document.getElementById("completeBtn").onclick=()=>{let d=ensure();d[today].done=!d[today].done;set(d);render()};
function stats(){let d=get(), t=d[today]||{ex:{}};let c=Object.values(t.ex||{}).filter(x=>x.done).length;document.getElementById("todayCount").textContent=c+"/8";document.getElementById("total").textContent=Object.values(d).filter(x=>x.done).length;document.getElementById("completeBtn").classList.toggle("done",!!t.done);document.getElementById("completeBtn").textContent=t.done?"Heute erledigt ✓":"Training heute erledigt ✓";streak(d)}
function streak(d){let s=0, cur=new Date();while(true){let k=cur.toISOString().slice(0,10);if(d[k]?.done){s++;cur.setDate(cur.getDate()-1)}else break}document.getElementById("streak").textContent=s}
function week(){let d=get(), labels=["Mo","Di","Mi","Do","Fr","Sa","So"], now=new Date(), off=now.getDay()===0?6:now.getDay()-1, mon=new Date(now);mon.setDate(now.getDate()-off);let w=document.getElementById("week");w.innerHTML="";for(let i=0;i<7;i++){let x=new Date(mon);x.setDate(mon.getDate()+i);let k=x.toISOString().slice(0,10);let div=document.createElement("div");div.className="day"+(d[k]?.done?" done":"");div.innerHTML=labels[i]+"<br>"+(d[k]?.done?"✓":"□");w.appendChild(div)}}
function history(){let d=get(), h=document.getElementById("history");h.innerHTML="";Object.keys(d).sort().reverse().forEach(k=>{let c=Object.values(d[k].ex||{}).filter(x=>x.done).length;h.innerHTML+=`<tr><td>${k}</td><td>${d[k].done?"✓":"-"}</td><td>${c}/8</td></tr>`})}
function chart(){let c=document.getElementById("chart"), ctx=c.getContext("2d"), d=get(), keys=Object.keys(d).sort().slice(-7);ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle="#f8fafc";ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle="#155eae";ctx.lineWidth=3;ctx.beginPath();keys.forEach((k,i)=>{let val=Object.values(d[k].ex||{}).filter(x=>x.done).length;let x=25+i*((c.width-50)/6||1), y=c.height-25-(val/8)*(c.height-55);i?ctx.lineTo(x,y):ctx.moveTo(x,y);ctx.fillStyle="#061525";ctx.fillText(k.slice(5),x-15,c.height-8)});ctx.stroke();keys.forEach((k,i)=>{let val=Object.values(d[k].ex||{}).filter(x=>x.done).length;let x=25+i*((c.width-50)/6||1), y=c.height-25-(val/8)*(c.height-55);ctx.fillStyle="#16a34a";ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fill()})}
let duration=30, rem=30, interval=null, running=false;function draw(){document.getElementById("timerDisplay").textContent=String(Math.floor(rem/60)).padStart(2,"0")+":"+String(rem%60).padStart(2,"0")}
document.querySelectorAll("[data-sec]").forEach(b=>b.onclick=()=>{duration=+b.dataset.sec;rem=duration;clearInterval(interval);running=false;document.getElementById("timerStatus").textContent="Bereit";draw()});
document.getElementById("startTimer").onclick=()=>{if(running)return;running=true;document.getElementById("timerStatus").textContent="Läuft";interval=setInterval(()=>{rem--;draw();if(rem<=0){clearInterval(interval);running=false;document.getElementById("timerStatus").textContent="Fertig";if(navigator.vibrate)navigator.vibrate([200,100,200]);alert("Zeit ist um!")}},1000)}
document.getElementById("pauseTimer").onclick=()=>{clearInterval(interval);running=false;document.getElementById("timerStatus").textContent="Pausiert"}
document.getElementById("resetTimer").onclick=()=>{clearInterval(interval);running=false;rem=duration;document.getElementById("timerStatus").textContent="Zurückgesetzt";draw()}
document.getElementById("clearBtn").onclick=()=>{if(confirm("Alle Daten löschen?")){localStorage.removeItem(key);render()}}
document.getElementById("exportBtn").onclick=()=>{let blob=new Blob([JSON.stringify(get(),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="calisthenics-daten.json";a.click()}
function render(){ensure();renderExercises();stats();week();history();chart();draw()} render();
if("serviceWorker" in navigator){navigator.serviceWorker.register("sw.js")}
